# Generated by Django 3.0.5 on 2022-01-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100, unique=True, verbose_name='Версия')),
                ('date_creation', models.DateTimeField(verbose_name='Дата создания')),
                ('status', models.SmallIntegerField(choices=[(1, 'Согласовано'), (2, 'Несогласовано')], default=2, verbose_name='Статус')),
                ('creator', models.CharField(max_length=30, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
                'ordering': ['version'],
                'get_latest_by': 'version',
            },
        ),
    ]
