# Generated by Django 3.0.5 on 2022-01-17 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField(max_length=250, verbose_name='Версия')),
                ('creator', models.CharField(max_length=30, verbose_name='Создатель')),
                ('start_date', models.DateTimeField(verbose_name='Время начала')),
                ('finish_date', models.DateTimeField(verbose_name='Время окончания')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Projects', verbose_name='Проект')),
                ('specification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='specifications.Specifications', verbose_name='Спецификация')),
            ],
            options={
                'verbose_name': 'Релиз',
                'verbose_name_plural': 'Релизы',
                'ordering': ['version'],
                'get_latest_by': 'version',
            },
        ),
    ]
