# Generated by Django 3.0.5 on 2022-01-17 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('status', models.SmallIntegerField(choices=[(1, 'Новое'), (2, 'Отвергнуто'), (3, 'Согласовано'), (4, 'Отменено'), (5, 'Реализовано'), (6, 'Нереализовано')], default=1, verbose_name='Статус')),
                ('type', models.SmallIntegerField(choices=[(None, 'Выберите тип требования'), (1, 'Функциональное'), (2, 'Нефункциональное')], default='Выберите тип требования', verbose_name='Тип требования')),
                ('date_creation', models.DateTimeField(verbose_name='Дата создания')),
                ('creator', models.CharField(max_length=30, verbose_name='Создатель')),
                ('executor', models.CharField(max_length=30, verbose_name='Исполнитель')),
                ('link_type', models.SmallIntegerField(blank=True, choices=[(1, 'Иерархическая'), (2, 'Зависимость')], null=True, verbose_name='Тип связи')),
                ('linked_requirement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='requirements.Requirements', verbose_name='Связанные требования')),
                ('specification', models.ForeignKey(blank=True, limit_choices_to={'status': 2}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='specifications.Specifications', verbose_name='Спецификация')),
            ],
            options={
                'verbose_name': 'Требование',
                'verbose_name_plural': 'Требования',
                'ordering': ['date_creation'],
                'get_latest_by': 'date_creation',
            },
        ),
    ]
