# Generated by Django 3.0.5 on 2022-01-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='linked_requirement',
        ),
        migrations.AddField(
            model_name='requirements',
            name='linked_requirement',
            field=models.ManyToManyField(blank=True, null=True, related_name='_requirements_linked_requirement_+', to='requirements.Requirements', verbose_name='Связанные требования'),
        ),
    ]
